### ISSUE TITLE
Sites Implementation - Frontend/UI

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-data-register#124]
**NOTE**: This ticket has now been broken down into the following tickets:

- #394 
- #395 
- #398 
- #399 
- #401 
- #402 

As a bc parks admin user I would like to view, find and edit sites so that I can easily view and make changes to a site when needed.

### Acceptance Criteria:
- [ ] UI matches the Figma designs
  - [ ] including designs and functionality outlined in notes:
    - [ ] Site header uses the same formatting as "Legal name" and "Historical name"
    - [ ] Links display the site ID in bold. Display the legal site name in normal. ex: **308-1**  Burton Site
    - [ ] Leading zeros on site IDs are not needed. (We will be removing the leading zeros from protected area IDs as well.)
    - [ ] Site links go to details page for that site.
- [ ] User can find site pages
- [ ] User can view sites
- [ ] User can edit sites

### Designs:
UIs and flows can be found on [Sites page of Figma file](https://www.figma.com/file/qdjegD6YHWZPlyFT8dGXvk/Park-Name-Data-Register?type=design&node-id=2096%3A3229&mode=design&t=M6ayrs5cjBcHqDKd-1) and attached below for reference.

![Image](https://github.com/bcgov/parks-data-register/assets/92062502/e0de90e8-780d-4340-9a49-5f84846032b8)
![Image](https://github.com/bcgov/parks-data-register/assets/92062502/315dccde-e051-4b07-8d2e-968b6a097aa1)
![Image](https://github.com/bcgov/parks-data-register/assets/92062502/4682fa37-383a-476e-a685-b56fb2af9a53)
![Image](https://github.com/bcgov/parks-data-register/assets/92062502/07cb8790-aa37-4889-bd76-eba7137a8587)
![Image](https://github.com/bcgov/parks-data-register/assets/92062502/97623793-241b-4573-bd74-245c8205815f)
![Image](https://github.com/bcgov/parks-data-register/assets/92062502/6f33cefa-f3b4-4fd2-9762-372d83b03d00)

### Notes:

- Blocked by #125 
- UI Designs for Sites #238 

From Nov 14th brainstorming session - sites need to:
- relate to parent protected area
- have naming convention
- relate to campgrounds
- have same edit process as protected area
- start as established, won't start as pending

Questions:
- How much additional data will there be with sites?
- How are sites added to the BCGW park layer?
- Site IDs - what to do with them?

Examples:
- example of legal site in BC laws: https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/00017_04#Cadamslake
- example of bcparks.ca display of legal site: https://bcparks.ca/adams-lake-marine-park/spillman-beaches-site/

**Comment by janemoxd** [comment]
Just commented on the bullet above "start as established, won't start as pending" - I'm not sure this is true so wondering where that came from?

**Comment by janemoxd** [comment]
Designs have been added but still need to be reviewed with the team and updated based on team feedback.

**Comment by ashley-dhillon** [comment]
Team reviewed the designs at refinement on Jan 9th with Glenna, Jane has a couple of takeaway questions related to Site ID's and the notes field she'll be running past Jessica and Rob and then reporting back on decision/outcome.

**Comment by janemoxd** [comment]
Just need @JLWade to sign off on the decision to remove leading zeros from IDs then these are good to go.

**Comment by Dianadec** [comment]
First ticket broken out: https://github.com/bcgov/parks-data-register/issues/394

**Comment by Dianadec** [comment]
**NOTE**: This ticket has now been broken down into the following tickets:

- #394 
- #395 
- #398 
- #399 
- #401 
- #402 

cc @JLWade

**Comment by JLWade** [comment]
Let's move this one to closed as work will be traked in other tickets mentioned above.
